load('imposterMScore1.mat');
load('MScore.mat');
MScore=as.MScore;
%negsample=zeros(length(imposterMScore),1);
negsample=(-1)*ones(length(imposterMScore),1);
%possample=ones(length(MScore),1);
possample=ones(length(MScore),1);
data=[MScore imposterMScore];
label=[possample' negsample'];
%plotroc(label,data);
%[tpr,fpr,thresholds] = roc(label,data);
[tpr,fpr] = roczz(label',data');
figure(100);
semilogx(fpr,tpr);
figure(101);
plot(fpr,tpr);
 xlable('FALSE POSITIVE RATE');
 ylable('TRUE POSITIVE RATE');
       title('RECEIVER OPERATING CHARACTERISTIC (ROC)');
grid on;
